

---
- name: Install and Configure Apache Atlas
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_user: gadet
    atlas_install_dir: /home/gadet/atlas
  tasks:
    - name: Download Apache Atlas source
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/atlas/2.4.0/apache-atlas-2.4.0-sources.tar.gz
        dest: /home/gadet/apache-atlas-2.4.0-sources.tar.gz
        owner: gadet
        group: gadet
        mode: '0644'

    - name: Extract Apache Atlas source
      ansible.builtin.unarchive:
        src: /home/gadet/apache-atlas-2.4.0-sources.tar.gz
        dest: /home/gadet/
        remote_src: yes
        owner: gadet
        group: gadet
        mode: '0755'

    - name: Install Maven
      ansible.builtin.apt:
        name: maven
        state: present
        update_cache: yes
      become: yes
      become_user: root


    - name: Ensure Atlas source directory is writable
      ansible.builtin.file:
        path: /home/gadet/apache-atlas-sources-2.4.0/
        owner: gadet
        group: gadet
        mode: 'u+rwx'
        recurse: yes
      become: yes
      become_user: root


    - name: Build Apache Atlas with Maven
      ansible.builtin.command:
        cmd: mvn clean -DskipTests package -Pdist,embedded-hbase-solr
        chdir: /home/gadet/apache-atlas-sources-2.4.0/
      environment:
        MAVEN_OPTS: "-Xms2g -Xmx2g"


    - name: Extract Apache Atlas server tarball to /opt/
      ansible.builtin.unarchive:
        src: /home/gadet/apache-atlas-sources-2.4.0/distro/target/apache-atlas-2.4.0-server.tar.gz
        dest: /opt/
        remote_src: yes
        owner: gadet
        group: gadet
        mode: '0775'
      become: yes
      become_user: root

    - name: Ensure Apache Atlas directory has correct ownership and permissions
      ansible.builtin.file:
        path: /opt/apache-atlas-2.4.0/
        owner: gadet
        group: gadet
        mode: '0775'
        recurse: yes
      become: yes
      become_user: root


    - name: Copy custom atlas-application.properties
      ansible.builtin.copy:
        src: files/atlas-application.properties
        dest: /opt/apache-atlas-2.4.0/conf/atlas-application.properties
        owner: gadet
        group: gadet
        mode: '0644'

    - name: Copy hbase-site.xml to Atlas conf/hbase directory
      ansible.builtin.copy:
        src: /opt/hbase-2.5.5-hadoop3/conf/hbase-site.xml
        dest: /opt/apache-atlas-2.4.0/conf/hbase/hbase-site.xml
        owner: gadet
        group: gadet
        mode: '0644'

    - name: Update atlas-env.sh settings
      lineinfile:
        path: /opt/apache-atlas-2.4.0/conf/atlas-env.sh
        regexp: '^export MANAGE_LOCAL_HBASE='
        line: 'export MANAGE_LOCAL_HBASE=false'

    - name: Update atlas-env.sh settings
      lineinfile:
        path: /opt/apache-atlas-2.4.0/conf/atlas-env.sh
        regexp: '^export MANAGE_LOCAL_SOLR='
        line: 'export MANAGE_LOCAL_SOLR=true'

    - name: Update atlas-env.sh settings
      lineinfile:
        path: /opt/apache-atlas-2.4.0/conf/atlas-env.sh
        regexp: '^export MANAGE_EMBEDDED_CASSANDRA='
        line: 'export MANAGE_EMBEDDED_CASSANDRA=false'

    - name: Update atlas-env.sh settings
      lineinfile:
        path: /opt/apache-atlas-2.4.0/conf/atlas-env.sh
        regexp: '^export MANAGE_LOCAL_ELASTICSEARCH='
        line: 'export MANAGE_LOCAL_ELASTICSEARCH=false'