---
- name: Start Hadoop Ecosystem and Apache Atlas
  hosts: localhost
  
  vars:
    zookeeper_lib_dir: /var/lib/zookeeper
    zookeeper_install_dir: /opt/apache-zookeeper-3.7.1-bin
    hadoop_dir: /opt/hadoop-3.3.2
    zookeeper_bin: /opt/apache-zookeeper-3.7.1-bin/bin/zkServer.sh
    hbase_home: /opt/hbase-2.5.5-hadoop3/
    kafka_home: /opt/kafka_2.11-2.2.0/
    hive_home: /opt/apache-hive-3.1.2-bin/
    atlas_home: /opt/apache-atlas-2.4.0
    atlas_start_script: "{{ atlas_home }}/bin/atlas_start.py"
    ansible_user: gadet

  tasks:
    - name: Fix permissions for Zookeeper directories
      file:
        path: "{{ item }}"
        owner: gadet
        group: gadet
        recurse: yes
        mode: "0755"
      become: yes
      with_items:
        - "{{ zookeeper_lib_dir }}"
        - "{{ zookeeper_install_dir }}"

    - name: Start Zookeeper if not running
      shell: pgrep -fl 'QuorumPeerMain' || true
      register: zookeeper_process
      ignore_errors: yes

    - name: Run Zookeeper start script
      shell: "{{ zookeeper_bin }} start"
      become: yes
      when: zookeeper_process.stdout == ""

    - name: Start all Hadoop daemons (start-all.sh)
      shell: "{{ hadoop_dir }}/sbin/start-all.sh"
      become: no

    - name: Start HBase if not running
      shell: pgrep -fl 'HMaster' || true
      register: hbase_process
      ignore_errors: yes

    - name: Run HBase start script
      shell: "{{ hbase_home }}/bin/start-hbase.sh"
      become: yes
      when: hbase_process.stdout == ""

    - name: Start Kafka if not running
      shell: pgrep -fl 'kafka.Kafka' || true
      register: kafka_process
      ignore_errors: yes

    - name: Start Kafka server
      shell: "{{ kafka_home }}/bin/kafka-server-start.sh {{ kafka_home }}/config/server.properties &"
      become: yes
      when: kafka_process.stdout == ""

    - name: Start Hive metastore if not running
      shell: pgrep -fl 'hive.metastore.HiveMetaStore' || true
      register: hive_metastore_process
      ignore_errors: yes

    - name: Start Hive metastore service
      shell: "hive --service metastore &"
      become: yes
      when: hive_metastore_process.stdout == ""

    - name: Start HiveServer2 if not running
      shell: pgrep -fl 'HiveServer2' || true
      register: hive_server_process
      ignore_errors: yes

    - name: Start HiveServer2 service
      shell: "hive --service hiveserver2 &"
      become: yes
      when: hive_server_process.stdout == ""

    - name: Check if Apache Atlas is running
      shell: pgrep -fl "python.*atlas_start.py" || true
      register: atlas_process
      ignore_errors: yes

    - name: Start Apache Atlas if not running
      shell: "{{ atlas_start_script }}"
      become: yes
      when: atlas_process.stdout == ""
